# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d83b34579a4a4672bf7ad1707c5de364d18228e110ebdac7e628fcdfdb1116001b757c577ffd29a7c54412fead4539928a0a2b406b86518e022e79edf346d8

test:
  secret_key_base: c87686f0de690c9b57ace7b686da7ec6ac48fa8894c5b7d72a242fcdc6afdf00c0c8ff78fb485fe182b3418621fe62b9c018f082010467cc789857da108e0225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
